config/routes.rb
Savemagnet::Application.routes.draw do
  
  devise_for :users 
  
  resources :magnets do
    collection do
      get 'delete_all'
    end
  end

  root :to => 'home#index'

end

app/models/magnet.rb
class Magnet < ActiveRecord::Base
  attr_accessible :url

  belongs_to :user

  validates :url, :length => {
    :minimum   => 10,
    :maximum   => 400
  }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :magnets, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/magnets_controller.rb
class MagnetsController < ApplicationController

  # GET /magnets
  # GET /magnets.json

  before_filter :authenticate_user!
  
  def index
    @magnets = current_user.magnets.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @magnets }
    end
  end

  # GET /magnets/1
  # GET /magnets/1.json
  def show
    @magnet = current_user.magnets.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @magnet }
    end
  end 

  # GET /magnets/new
  # GET /magnets/new.json
  def new    
    @magnet = Magnet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @magnet }
    end
  end

  # GET /magnets/1/edit
  def edit

    @magnet = current_user.magnets.find(params[:id])

  end

  # POST /magnets
  # POST /magnets.json
  def create

    url = params[:magnet][:url].split(/[\n]/)

    # Splitting the list in a new line and save
    url.each do |u|
      params[:magnet][:url] = u
      @magnet = current_user.magnets.create(params[:magnet])
    end

    respond_to do |format|
      if @magnet.save
        format.html { redirect_to magnets_path, notice: 'Magnet was successfully created.' }
        format.json { render json: @magnet, status: :created, location: @magnet }
      else
        format.html { render action: "new" }
        format.json { render json: @magnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /magnets/1
  # PUT /magnets/1.json
  def update
    @magnet = current_user.magnets.find(params[:id])

    respond_to do |format|
      if @magnet.update_attributes(params[:magnet])
        format.html { redirect_to @magnet, notice: 'Magnet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @magnet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /magnets/1
  # DELETE /magnets/1.json
  def destroy
    @magnet = current_user.magnets.find(params[:id])
    @magnet.destroy

    respond_to do |format|
      format.html { redirect_to magnets_url }
      format.json { head :no_content }
    end
  end

  def delete_all

    @magnets = current_user.magnets.all
    @magnets.each do |magnet|
      magnet.destroy
    end    

    respond_to do |format|
      format.html { redirect_to magnets_url }
      format.json { head :no_content }
    end    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/magnets_helper.rb
module MagnetsHelper
end

app/views/home/index.html.haml
/- model_class = Home

/#user_nav

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis lacinia mollis tellus, eget auctor dolor posuere sed. Nullam fermentum risus eu sapien molestie accumsan. Etiam cursus nulla sit amet nibh ullamcorper scelerisque mattis nunc dictum. Morbi bibendum arcu vel felis bibendum auctor ut a nisl. Aenean scelerisque neque at massa iaculis ut iaculis massa dignissim. Vivamus lorem enim, lobortis eu vehicula ut, volutpat non risus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse posuere condimentum semper. Aliquam ligula purus, vehicula vel aliquet ut, vulputate sed mi. Suspendisse eu leo ut nulla tempor ornare non sit amet nunc. Aliquam sagittis rhoncus turpis ac consequat. Sed eros urna, sagittis at sagittis quis, imperdiet eget lectus. Curabitur sit amet nisl ac turpis molestie vulputate a nec sem. Maecenas elit sapien, viverra at vestibulum et, vehicula eget est. In tincidunt tincidunt nisi, quis eleifend lorem elementum sit amet. Donec imperdiet est nec nibh interdum sed rhoncus lectus vulputate.

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Savemagnet"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="favicon.ico" rel="shortcut icon")

  %body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Savemagnet
          .container.nav-collapse
            %ul.nav
              - if user_signed_in?
                %li= link_to current_user.email
                %li= link_to "Sign out", destroy_user_session_path, :method => :delete
              - else                
                %li= link_to "Sign up", new_user_registration_path
                %li= link_to "Sign in", new_user_session_path

    .container-fluid

      .row-fluid
        .span3
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Menu
              %li= link_to "Add magnet list", new_magnet_path
              %li= link_to "View magnet list", magnets_path
              %li= link_to "Delete all magnet link", delete_all_magnets_path, data: { confirm: 'Are you sure?' }
        .span9
          = bootstrap_flash
          = yield
    
      %footer
        %p &copy; SaveMagnet 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    %script{:src=>"//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js"}
    %script{:src=>"//ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular-resource.min.js"}
    = javascript_include_tag "application"

app/views/magnets/_form.html.haml
= form_for @magnet, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :url, :class => 'control-label'
    .controls
      = f.text_area :url, :rows => 5, :class => 'text_area', :class => "span10", :placeholder => 'Paste magnet list...'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), magnets_path, :class => 'btn'

app/views/magnets/edit.html.haml
- model_class = Magnet
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/magnets/index.html.haml
- model_class = Magnet

.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      
      %th= model_class.human_attribute_name(:url)
      
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @magnets.each do |magnet|
    - magnet_name = magnet.url.match(/(?<=dn=)(.+?)(?=&|$)/)
      %tr
        
        %td 
          = link_to (URI.unescape(magnet_name.to_s)), magnet.url
        
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_magnet_path(magnet), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), magnet_path(magnet), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_magnet_path, :class => 'btn btn-primary'

app/views/magnets/new.html.haml
- model_class = Magnet
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/magnets/show.html.haml
- model_class = Magnet
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:url) + ':'
  %br
  = @magnet.url

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), magnets_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_magnet_path(@magnet), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), magnet_path(@magnet), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'